import * as path from 'node:path'
import type { ConfigRoutePath } from './config-parser'
import type { FileRouteNode } from './tree-builder'
import { collectRoutePaths } from './tree-builder'

export interface CodegenOptions {
	/** The route tree from file scanning. */
	tree: FileRouteNode[]
	/** Absolute path to the routes directory. */
	routesDir: string
	/** Absolute path to the output file. */
	outputPath: string
}

/**
 * Generate the buzola.gen.ts file with:
 * 1. Module augmentation for BuzolaRouteMap (type safety)
 * 2. Route tree construction code
 */
export function generateRouteModule(options: CodegenOptions): string {
	const { tree, routesDir, outputPath } = options
	const outputDir = path.dirname(outputPath)
	let importCounter = 0

	const lines: string[] = []

	lines.push('// This file is auto-generated by @buzola/vite-plugin. Do not edit.')
	lines.push('/* eslint-disable */')
	lines.push('')

	// Framework imports first — needed by lazy component declarations below
	lines.push(`import { lazy, type ComponentType } from 'react';`)
	lines.push(`import { buildRouteTree } from 'buzola';`)
	lines.push(`import type { RouteConfig } from 'buzola';`)
	lines.push('')

	// Collect route imports — importsByAbsPath maps absolute file path → import info
	const imports: { varName: string; filePath: string; isLazy: boolean }[] = []
	const importsByAbsPath = new Map<string, { varName: string; isLazy: boolean }>()
	collectImports(tree, outputDir, imports, importsByAbsPath, () => importCounter++)

	// Generate route imports
	for (const imp of imports) {
		if (imp.isLazy) {
			lines.push(`const ${imp.varName} = () => import('${imp.filePath}') as Promise<{ default: ComponentType }>;`)
		} else {
			lines.push(`import ${imp.varName} from '${imp.filePath}';`)
		}
	}

	lines.push('')

	// Generate route map type augmentation
	const routePaths = collectRoutePaths(tree)
	lines.push('// Module augmentation for type-safe routing')
	lines.push(`declare module 'buzola' {`)
	lines.push('  interface BuzolaRouteMap {')
	for (const route of routePaths) {
		if (route.params.length === 0) {
			lines.push(`    '${route.path}': {};`)
		} else {
			const paramEntries = route.params.map(p => `${p}: string`).join('; ')
			lines.push(`    '${route.path}': { ${paramEntries} };`)
		}
	}
	lines.push('  }')
	lines.push('}')
	lines.push('')

	// Generate route tree config
	lines.push('const routeConfigs: RouteConfig[] = [')
	generateTreeConfig(tree, lines, importsByAbsPath, 1)
	lines.push('];')
	lines.push('')
	lines.push('export const routes = buildRouteTree(routeConfigs);')
	lines.push('')

	return lines.join('\n')
}

function collectImports(
	nodes: FileRouteNode[],
	outputDir: string,
	imports: { varName: string; filePath: string; isLazy: boolean }[],
	importsByAbsPath: Map<string, { varName: string; isLazy: boolean }>,
	nextId: () => number,
): void {
	for (const node of nodes) {
		if (node.filePath) {
			const relativePath = path.relative(outputDir, node.filePath)
			const importPath = relativePath.startsWith('.') ? relativePath : `./${relativePath}`
			// Strip extension for import
			const cleanPath = importPath.replace(/\.(tsx?|jsx?)$/, '')
			const varName = `Route${nextId()}`
			const isLazy = !node.isLayout // Layouts are eagerly loaded, pages are lazy
			imports.push({ varName, filePath: cleanPath, isLazy })
			importsByAbsPath.set(node.filePath, { varName, isLazy })
		}

		collectImports(node.children, outputDir, imports, importsByAbsPath, nextId)
	}
}

function generateTreeConfig(
	nodes: FileRouteNode[],
	lines: string[],
	importsByAbsPath: Map<string, { varName: string; isLazy: boolean }>,
	indent: number,
): void {
	const pad = '  '.repeat(indent)

	for (const node of nodes) {
		const imp = node.filePath ? importsByAbsPath.get(node.filePath) : undefined

		lines.push(`${pad}{`)
		lines.push(`${pad}  path: '${node.segment ? `/${node.segment}` : '/'}',`)

		if (imp) {
			if (imp.isLazy) {
				lines.push(`${pad}  component: lazy(${imp.varName}),`)
			} else {
				lines.push(`${pad}  component: ${imp.varName},`)
			}
		}

		if (node.isLayout) lines.push(`${pad}  isLayout: true,`)
		if (node.isIndex) lines.push(`${pad}  isIndex: true,`)
		if (node.isPathlessGroup) lines.push(`${pad}  isPathlessGroup: true,`)

		if (node.children.length > 0) {
			lines.push(`${pad}  children: [`)
			generateTreeConfig(node.children, lines, importsByAbsPath, indent + 2)
			lines.push(`${pad}  ],`)
		}

		lines.push(`${pad}},`)
	}
}

/**
 * Generate a type-only augmentation file from config-based route paths.
 *
 * Unlike `generateRouteModule`, this produces no component imports or route tree —
 * just the `BuzolaRouteMap` module augmentation for type safety.
 */
export function generateConfigTypeAugmentation(routes: ConfigRoutePath[]): string {
	const lines: string[] = []

	lines.push('// This file is auto-generated by @buzola/vite-plugin. Do not edit.')
	lines.push('/* eslint-disable */')
	lines.push('')
	lines.push(`declare module 'buzola' {`)
	lines.push('  interface BuzolaRouteMap {')

	for (const route of routes) {
		if (route.params.length === 0) {
			lines.push(`    '${route.path}': {};`)
		} else {
			const paramEntries = route.params.map(p => `${p}: string`).join('; ')
			lines.push(`    '${route.path}': { ${paramEntries} };`)
		}
	}

	lines.push('  }')
	lines.push('}')
	lines.push('')

	return lines.join('\n')
}

/**
 * Generate the virtual module content for `virtual:buzola/routes`.
 */
export function generateVirtualModule(outputPath: string): string {
	return `export { routes } from '${outputPath.replace(/\.ts$/, '')}';\n`
}
