import * as path from 'node:path'
import type { FileRouteNode } from './tree-builder.js'

export interface CodegenOptions {
	/** The route tree from file scanning. */
	tree: FileRouteNode[]
	/** Absolute path to the routes directory. */
	routesDir: string
	/** Absolute path to the output file. */
	outputPath: string
	/** Parameter names that should be persistent across navigations. */
	persistentParams?: string[]
}

/**
 * Generate the buzola.gen.ts file with:
 * 1. Module augmentation for BuzolaPageMap (type safety)
 * 2. Page registry (page ID → route pattern)
 * 3. Route tree construction code
 */
export function generateRouteModule(options: CodegenOptions): string {
	const { tree, outputPath } = options
	const outputDir = path.dirname(outputPath)
	let importCounter = 0

	const lines: string[] = []

	lines.push('// This file is auto-generated by @buzola/vite-plugin. Do not edit.')
	lines.push('/* eslint-disable */')
	lines.push('')

	// Framework imports first — needed by lazy component declarations below
	lines.push(`import { lazy, type ComponentType } from 'react';`)
	lines.push(`import { buildRouteTree } from '@buzola/router';`)
	lines.push(`import type { RouteConfig } from '@buzola/router';`)
	lines.push('')

	// Collect route imports — importsByKey maps "filePath::exportName" → import info
	const imports: { varName: string; filePath: string; isLazy: boolean; exportName: string }[] = []
	const importsByKey = new Map<string, { varName: string; isLazy: boolean }>()
	collectImports(tree, outputDir, imports, importsByKey, () => importCounter++)

	// Generate route imports
	for (const imp of imports) {
		if (imp.isLazy) {
			lines.push(
				`const ${imp.varName} = () => import('${imp.filePath}').then(m => ({ default: m.${imp.exportName}.component })) as Promise<{ default: ComponentType }>;`,
			)
		} else {
			if (imp.exportName !== 'default') {
				lines.push(`import { ${imp.exportName} as ${imp.varName} } from '${imp.filePath}';`)
			} else {
				lines.push(`import ${imp.varName} from '${imp.filePath}';`)
			}
		}
	}

	lines.push('')

	// Collect page info for type augmentation and registry
	const pages = collectPages(tree)

	// Generate page map type augmentation
	lines.push('// Module augmentation for type-safe page-centric routing')
	lines.push(`declare module '@buzola/router' {`)
	lines.push('  interface BuzolaPageMap {')
	for (const page of pages) {
		if (page.params.length === 0) {
			lines.push(`    '${page.pageId}': {};`)
		} else {
			const paramEntries = page.params.map(p => {
				const type = p.array ? 'string[]' : 'string'
				return p.optional ? `${p.name}?: ${type}` : `${p.name}: ${type}`
			}).join('; ')
			lines.push(`    '${page.pageId}': { ${paramEntries} };`)
		}
	}
	lines.push('  }')
	if (options.persistentParams && options.persistentParams.length > 0) {
		lines.push('  interface BuzolaPersistentParams {')
		for (const param of options.persistentParams) {
			lines.push(`    ${param}: true;`)
		}
		lines.push('  }')
	}
	lines.push('}')
	lines.push('')

	// Generate page registry
	lines.push('// Page registry — page ID → route pattern')
	lines.push('export const pageRegistry: Record<string, string> = {')
	for (const page of pages) {
		lines.push(`  '${page.pageId}': '${page.routePattern}',`)
	}
	lines.push('};')
	lines.push('')

	// Generate route tree config
	lines.push('const routeConfigs: RouteConfig[] = [')
	generateTreeConfig(tree, lines, importsByKey, 1)
	lines.push('];')
	lines.push('')
	lines.push('export const routes = buildRouteTree(routeConfigs);')
	lines.push('')

	return lines.join('\n')
}

interface PageInfo {
	pageId: string
	routePattern: string
	params: { name: string; optional: boolean; array: boolean }[]
}

/**
 * Collect page info from the file route tree for codegen.
 */
function collectPages(nodes: FileRouteNode[]): PageInfo[] {
	const result: PageInfo[] = []

	for (const node of nodes) {
		if (node.filePath && !node.isLayout && !node.isNotFound) {
			if (node.pageExports) {
				for (const exp of node.pageExports) {
					result.push({
						pageId: exp.pageId,
						routePattern: exp.routePattern,
						params: exp.params,
					})
				}
			}
		}

		if (node.children.length > 0) {
			result.push(...collectPages(node.children))
		}
	}

	return result
}

function importKey(filePath: string, exportName?: string): string {
	return `${filePath}::${exportName ?? 'default'}`
}

function collectImports(
	nodes: FileRouteNode[],
	outputDir: string,
	imports: { varName: string; filePath: string; isLazy: boolean; exportName: string }[],
	importsByKey: Map<string, { varName: string; isLazy: boolean }>,
	nextId: () => number,
): void {
	for (const node of nodes) {
		if (node.filePath) {
			const key = importKey(node.filePath, node.exportName)
			if (!importsByKey.has(key)) {
				const relativePath = path.relative(outputDir, node.filePath).replaceAll('\\', '/')
				const importPath = relativePath.startsWith('.') ? relativePath : `./${relativePath}`
				// Strip extension for import
				const cleanPath = importPath.replace(/\.(tsx?|jsx?)$/, '')
				const varName = `Route${nextId()}`
				const isLazy = !node.isLayout // Layouts are eagerly loaded, pages are lazy
				const exportName = node.exportName ?? 'default'
				imports.push({ varName, filePath: cleanPath, isLazy, exportName })
				importsByKey.set(key, { varName, isLazy })
			}
		}

		collectImports(node.children, outputDir, imports, importsByKey, nextId)
	}
}

function generateTreeConfig(
	nodes: FileRouteNode[],
	lines: string[],
	importsByKey: Map<string, { varName: string; isLazy: boolean }>,
	indent: number,
): void {
	const pad = '  '.repeat(indent)

	for (const node of nodes) {
		const imp = node.filePath ? importsByKey.get(importKey(node.filePath, node.exportName)) : undefined

		lines.push(`${pad}{`)
		lines.push(`${pad}  path: '${node.segment ? `/${node.segment}` : '/'}',`)

		// Emit matchPath when page has a custom route pattern that differs from file-hierarchy position
		if (node.pageExports && node.pageExports.length > 0 && node.pageExports[0].routePattern !== node.fullPath) {
			lines.push(`${pad}  matchPath: '${node.pageExports[0].routePattern}',`)
		}

		if (imp) {
			if (imp.isLazy) {
				lines.push(`${pad}  component: lazy(${imp.varName}),`)
				lines.push(`${pad}  preload: ${imp.varName},`)
			} else {
				lines.push(`${pad}  component: ${imp.varName},`)
			}
		}

		if (node.isLayout) lines.push(`${pad}  isLayout: true,`)
		if (node.isIndex) lines.push(`${pad}  isIndex: true,`)
		if (node.isPathlessGroup) lines.push(`${pad}  isPathlessGroup: true,`)

		if (node.children.length > 0) {
			lines.push(`${pad}  children: [`)
			generateTreeConfig(node.children, lines, importsByKey, indent + 2)
			lines.push(`${pad}  ],`)
		}

		lines.push(`${pad}},`)
	}
}
