import { LoaderCache } from './loader-cache.js'
import { matchRoutes } from './matcher.js'
import type { BlockerFn, NavigateOptions, NavigationAdapter, RouterState, RouteTree } from './types.js'
import { extractParamNames, isSamePath, parseParamSegment } from './utils.js'

/**
 * Thrown when a route guard prevents navigation.
 */
export class NavigationAbortedError extends Error {
	constructor() {
		super('Navigation aborted by blocker')
		this.name = 'NavigationAbortedError'
	}
}

export type RouterSubscriber = (state: RouterState) => void

export interface RouterOptions {
	/** Route tree (segment trie). */
	routes: RouteTree
	/** Navigation adapter (browser or memory). */
	adapter: NavigationAdapter
	/** Enable View Transitions API for navigations. */
	viewTransitions?: boolean
	/**
	 * Base path prefix for all routes (e.g., "/app").
	 * Routes are defined without the base path; the router prepends it
	 * for navigation and strips it for matching.
	 */
	basePath?: string
	/**
	 * Callback that returns fallback values for persistent parameters.
	 * Used when a persistent param is not explicitly provided and not present in the current URL.
	 */
	persistentParams?: () => Record<string, string>
	/**
	 * Page registry mapping page IDs to route patterns.
	 * Generated by the Vite plugin.
	 */
	pageRegistry?: Record<string, string>
	/**
	 * Maximum number of entries in the global loader cache (shared across all pages).
	 * When navigating back to a cached URL, stale data is shown immediately
	 * while a background reload runs (SWR).
	 * Set to 0 to always re-fetch on URL change (default).
	 */
	loaderCacheSize?: number
}

/**
 * Central Router orchestrator.
 * Intercepts all navigations via the Navigation API and manages route matching.
 */
export class Router {
	private routes: RouteTree
	private adapter: NavigationAdapter
	private viewTransitions: boolean
	private readonly _basePath: string
	private readonly persistentParamsFn?: () => Record<string, string>
	private readonly pageRegistry: Record<string, string>
	private subscribers = new Set<RouterSubscriber>()
	private invalidationListeners = new Set<() => void>()
	private state: RouterState
	private navigationId = 0
	private stopFn: (() => void) | undefined
	private blockers = new Set<BlockerFn>()
	private pendingScrollBehavior: 'after-transition' | 'manual' = 'after-transition'
	private pendingFocusReset: 'after-transition' | 'manual' | undefined
	private readonly _loaderCache: LoaderCache | undefined

	constructor(options: RouterOptions) {
		this.routes = options.routes
		this.adapter = options.adapter
		this.viewTransitions = options.viewTransitions ?? false
		this._basePath = options.basePath ? options.basePath.replace(/\/$/, '') : ''
		this.persistentParamsFn = options.persistentParams
		this.pageRegistry = options.pageRegistry ?? {}
		this._loaderCache = options.loaderCacheSize ? new LoaderCache(options.loaderCacheSize) : undefined

		// Initialize state from current URL
		const url = this.adapter.getCurrentURL()
		const matchUrl = this.createMatchUrl(url)
		const matches = matchRoutes(this.routes, matchUrl) ?? []

		if (matches.length === 0) {
			console.warn(`[buzola] No route matched URL "${url.pathname}". Define a catch-all 404 route to handle unmatched URLs.`)
		}

		this.state = {
			location: url,
			matches,
			isPending: false,
			navigationState: this.adapter.getState(),
		}
	}

	/**
	 * The configured base path (e.g., "/app"). Empty string if none.
	 */
	get basePath(): string {
		return this._basePath
	}

	/**
	 * Global LRU cache for page loader data, shared across all page components.
	 * Undefined when loaderCacheSize is 0 (no caching).
	 */
	get loaderCache(): LoaderCache | undefined {
		return this._loaderCache
	}

	/**
	 * Get the current router state.
	 */
	getState(): RouterState {
		return this.state
	}

	/**
	 * Subscribe to state changes. Returns an unsubscribe function.
	 */
	subscribe(subscriber: RouterSubscriber): () => void {
		this.subscribers.add(subscriber)
		return () => {
			this.subscribers.delete(subscriber)
		}
	}

	/**
	 * Start intercepting navigations.
	 * Call this once when the router is initialized.
	 */
	start(): () => void {
		const handler = (event: import('./types.js').BuzolaNavigateEvent) => {
			// Consume the pending options before any early return — they belong to the
			// navigation that armed them and must not leak into the next one.
			const scrollBehavior = this.pendingScrollBehavior
			const explicitFocusReset = this.pendingFocusReset
			this.pendingScrollBehavior = 'after-transition'
			this.pendingFocusReset = undefined

			if (!event.canIntercept) return

			const url = new URL(event.destination.url)
			const matchUrl = this.createMatchUrl(url)
			const matches = matchRoutes(this.routes, matchUrl)
			if (!matches) {
				console.warn(`[buzola] No route matched URL "${url.pathname}". The navigation was not intercepted.`)
				return
			}

			const currentNavId = ++this.navigationId
			const useViewTransition = event.viewTransition || this.viewTransitions
			// Query-only navigations stay on the same page — keep focus where the user left it
			// (search boxes, filters, pagination). Path changes keep the browser's focus reset,
			// and so do fragment changes, which must move focus to the targeted section.
			const focusReset = explicitFocusReset
				?? (isSamePath(this.state.location, url) && this.state.location.hash === url.hash ? 'manual' : 'after-transition')

			event.intercept({
				scroll: scrollBehavior,
				focusReset,
				handler: async () => {
					// Check blockers before setting pending state
					for (const blocker of this.blockers) {
						if (this.navigationId !== currentNavId) return
						const shouldProceed = await blocker()
						if (!shouldProceed) {
							throw new NavigationAbortedError()
						}
					}

					// Set pending state with target location
					this.setState({
						...this.state,
						isPending: true,
						pendingLocation: url,
					})

					// A newer navigation has started — abandon this one
					if (this.navigationId !== currentNavId) return

					// Perform the DOM update
					const doUpdate = () => {
						const previousHref = this.state.location.href
						this.setState({
							location: url,
							matches,
							isPending: false,
							pendingLocation: undefined,
							navigationState: this.adapter.getState(),
						})
						// Going to the URL we are already on is still a navigation — a browser
						// re-requests the document for it. Loader data is keyed by href, so it
						// would silently keep serving stale data without an explicit invalidation.
						if (previousHref === url.href) {
							this.invalidateAll()
						}
					}

					if (useViewTransition && typeof document !== 'undefined' && 'startViewTransition' in document) {
						;(document as unknown as { startViewTransition: (cb: () => void) => void }).startViewTransition(doUpdate)
					} else {
						doUpdate()
					}
				},
			})
		}

		this.adapter.addEventListener('navigate', handler)

		const stop = () => {
			this.adapter.removeEventListener('navigate', handler)
		}
		this.stopFn = stop

		return stop
	}

	/**
	 * Navigate programmatically.
	 * The `to` path should not include the base path — it is prepended automatically.
	 */
	navigate(to: string, options?: NavigateOptions): void {
		if (options?.resetScroll === false) {
			this.pendingScrollBehavior = 'manual'
		}
		if (options?.focusReset) {
			this.pendingFocusReset = options.focusReset
		}
		this.adapter.navigate(this._basePath + to, options)
	}

	/**
	 * Navigate to a page by its page ID.
	 * Looks up the route pattern from the page registry and builds the URL.
	 */
	navigateToPage(pageId: string, params?: Record<string, string>, options?: NavigateOptions): void {
		const path = this.buildPagePath(pageId, params)
		this.navigate(this.stripBasePath(path), options)
	}

	/**
	 * Build a URL path for a page ID with the given params.
	 * Path params are substituted into the route pattern; extra params become query string.
	 */
	buildPagePath(pageId: string, params?: Record<string, string>): string {
		const pattern = this.pageRegistry[pageId]
		if (!pattern) {
			throw new Error(`[buzola] Unknown page "${pageId}". Is it registered in the page registry?`)
		}
		const resolved = this.resolveParams(pattern, params)
		return this.buildPath(pattern, resolved)
	}

	/**
	 * Preload a page by its page ID.
	 * Triggers lazy component imports for all matching route nodes,
	 * so the code is ready when the user navigates.
	 */
	preload(pageId: string, params?: Record<string, string>): void {
		const path = this.buildPagePath(pageId, params)
		const url = new URL(path, 'http://localhost')
		const matchUrl = this.createMatchUrl(url)
		const matches = matchRoutes(this.routes, matchUrl)
		if (!matches) return
		for (const match of matches) {
			match.node.preload?.()
		}
	}

	/**
	 * Go back in history.
	 */
	back(): void {
		this.adapter.back()
	}

	/**
	 * Go forward in history.
	 */
	forward(): void {
		this.adapter.forward()
	}

	/**
	 * Build a URL from a path pattern and params.
	 * The returned path includes the base path prefix.
	 */
	buildPath(pattern: string, params?: Record<string, string>): string {
		const segments = pattern.split('/')
		const result: string[] = []
		const missing: string[] = []

		for (const segment of segments) {
			if (segment.startsWith(':')) {
				const { name: paramName, isCatchAll } = parseParamSegment(segment)
				const value = params?.[paramName]
				if (value === undefined) {
					missing.push(paramName)
				} else {
					if (isCatchAll) {
						// Catch-all values may contain slashes — insert raw
						result.push(value)
					} else {
						result.push(encodeURIComponent(value))
					}
				}
			} else {
				result.push(segment)
			}
		}

		if (missing.length > 0) {
			if (!params) {
				throw new Error(`[buzola] Missing params for path "${pattern}": ${missing.join(', ')}`)
			}
			throw new Error(`[buzola] Missing param "${missing[0]}" for path "${pattern}"`)
		}

		// Extra params (not in path pattern) → query string
		const pathParamNames = new Set(extractParamNames(pattern))
		const search = new URLSearchParams()
		if (params) {
			for (const [key, value] of Object.entries(params)) {
				if (!pathParamNames.has(key) && value !== undefined) {
					search.set(key, value)
				}
			}
		}

		const path = this._basePath + result.join('/')
		const qs = search.toString()
		return qs ? `${path}?${qs}` : path
	}

	/**
	 * Strip the base path prefix from a pathname.
	 * Returns the pathname relative to the base path.
	 */
	stripBasePath(pathname: string): string {
		if (this._basePath && pathname.startsWith(this._basePath)) {
			return pathname.slice(this._basePath.length) || '/'
		}
		return pathname
	}

	/**
	 * Resolve params for a route pattern by merging:
	 * 1. Explicitly provided params (highest priority)
	 * 2. Current URL match params
	 * 3. persistentParams() callback (fallback)
	 *
	 * Only fills params that are present in the target pattern.
	 */
	resolveParams(pattern: string, explicitParams?: Record<string, string>): Record<string, string> {
		const paramNames = extractParamNames(pattern)
		const currentParams = this.getCurrentParams()
		const fallbackParams = this.persistentParamsFn?.() ?? {}
		const result: Record<string, string> = {}

		for (const name of paramNames) {
			const value = explicitParams?.[name] ?? currentParams[name] ?? fallbackParams[name]
			if (value !== undefined) {
				result[name] = value
			}
		}

		// Pass through extra explicit params (not in pattern) for search params
		if (explicitParams) {
			const pathParamNames = new Set(paramNames)
			for (const [key, value] of Object.entries(explicitParams)) {
				if (!pathParamNames.has(key) && value !== undefined) {
					result[key] = value
				}
			}
		}

		return result
	}

	/**
	 * Get merged params from all current route matches.
	 */
	private getCurrentParams(): Record<string, string> {
		const params: Record<string, string> = {}
		for (const match of this.state.matches) {
			Object.assign(params, match.params)
		}
		return params
	}

	/**
	 * Trigger all registered invalidation listeners.
	 * Used to re-run page loaders in the background.
	 */
	invalidateAll(): void {
		for (const listener of this.invalidationListeners) {
			listener()
		}
	}

	/**
	 * Register an invalidation listener. Returns an unsubscribe function.
	 */
	onInvalidate(listener: () => void): () => void {
		this.invalidationListeners.add(listener)
		return () => {
			this.invalidationListeners.delete(listener)
		}
	}

	/**
	 * Register a navigation blocker.
	 * The blocker function is called before each navigation.
	 * It must return a Promise that resolves to `true` to allow or `false` to block.
	 * Returns an unsubscribe function.
	 */
	addBlocker(fn: BlockerFn): () => void {
		this.blockers.add(fn)
		return () => {
			this.blockers.delete(fn)
		}
	}

	/**
	 * Dispose the router — clear all subscribers and reset state.
	 */
	dispose(): void {
		this.stopFn?.()
		this.stopFn = undefined
		this.subscribers.clear()
		this.invalidationListeners.clear()
	}

	/**
	 * Update the route tree (for HMR).
	 */
	updateRoutes(routes: RouteTree): void {
		this.routes = routes
		// Re-match current URL with new routes
		const matches = matchRoutes(this.routes, this.createMatchUrl(this.state.location)) ?? []
		this.setState({
			...this.state,
			matches,
		})
	}

	/**
	 * Create a URL with basePath stripped for route matching.
	 */
	private createMatchUrl(url: URL): URL {
		if (!this._basePath) return url
		const stripped = new URL(url)
		stripped.pathname = this.stripBasePath(stripped.pathname)
		return stripped
	}

	private setState(newState: RouterState): void {
		this.state = newState
		for (const subscriber of this.subscribers) {
			subscriber(this.state)
		}
	}
}
